### ISSUE TITLE
Onto-ns expects entity in the "wrong" format

### ISSUE THREAD

**Issue by sygout** [SINTEF/dlite-entities-service#38]
Some DLite entites are defined with an array of dimensions and an array of properties. onto-ns seems to expect that to be a dictionnary of dimensions or properties. 

Test: 
 - not working: http://onto-ns.com/meta/1.0/OPTIMADEStructure
 - working: http://onto-ns.com/meta/1.0/OPTIMADEStructureSpecies

As it is, the problem is solved by converting the array to dictionnaries. It would be better if it can handle the array case.

**Comment by CasperWA** [comment]
Could you please give a reference to the array data model? What do to the arrays look like?

**Comment by sygout** [comment]
The references are the two examples of entities stored in the Atlas MongoDB.

**Comment by sygout** [comment]
You can also have a look here https://gitlab.sintef.no/team40/demonstrators/mylittledemo-datamodel/-/tree/main/tests/data) and see the difference between premod_simple_ version 0.1 and 0.2

**Comment by CasperWA** [comment]
Ah, I meant more an example of the array data models, not the dict data models, which already exists. I'll take a look in GitLab links - cheers 👍

**Comment by CasperWA** [comment]
Hmm. Starting to implement this I was thinking: The models currently used in the service are only meant for the "returned" entities, i.e., not to validate the created entities.
Why not instead ensure the old SOFT5-style data models are converted to SOFT7-style models upon upload or on-the-fly between finding them in the backend and serving them?
